//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_players
    {
        public int id { get; set; }
        public int upcomings_id { get; set; }
        public int player_id { get; set; }
    
        public virtual playerInfo playerInfo { get; set; }
        public virtual Upcoming Upcoming { get; set; }
    }
}
