//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upcoming
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Upcoming()
        {
            this.Match_players = new HashSet<Match_players>();
        }
    
        public int id { get; set; }
        public int slot_id { get; set; }
        public int coach_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual coachInfo coachInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_players> Match_players { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
